name: Publicera webbplatsen

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Hämta webbplatsen från main
        uses: actions/checkout@v4

      - name: Konfigurera GitHub Pages
        uses: actions/configure-pages@v5

      - name: Skapa publiceringspaket
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

      - name: Publicera webbplatsen
        id: deployment
        uses: actions/deploy-pages@v4
